# Generated by Django 2.2.24 on 2021-06-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_class_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('class_code', models.CharField(max_length=6)),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
