# Generated by Django 2.2.24 on 2021-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='location',
            field=models.FileField(default=0, upload_to='submission'),
            preserve_default=False,
        ),
    ]
