# Generated by Django 2.2.24 on 2021-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_assignment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
