# Generated by Django 2.2.24 on 2021-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='location',
            field=models.FileField(upload_to='submission/'),
        ),
    ]
