# Generated by Django 2.2.24 on 2021-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210612_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('class_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=254)),
            ],
        ),
    ]
