# Generated by Django 2.2.24 on 2021-06-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=10)),
                ('class_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=254)),
            ],
        ),
    ]
