# Generated by Django 2.2.24 on 2021-06-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='location',
            field=models.FileField(default=0, upload_to='student/'),
            preserve_default=False,
        ),
    ]
