# Generated by Django 2.2.24 on 2021-06-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='location_sample',
            field=models.FileField(default=0, upload_to='sample/'),
            preserve_default=False,
        ),
    ]
